spring :
  profiles:
    active: production

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3306/studentdb
    username: root
  jpa:
    hibernate:
      ddl-auto: create

welcome:
  message: "welcome to dev"
